// nationalityUtils.js

const nationalityToAlpha2 = {
    // Mapping of Nationalities to Alpha2 Codes:
    'Afghan': 'AF',
    'Åland Island': 'AX',
    'Albanian': 'AL',
    'Algerian': 'DZ',
    'American Samoan': 'AS',
    'Andorran': 'AD',
    'Angolan': 'AO',
    'Anguillan': 'AI',
    'Antarctic': 'AQ',
    'Antiguan or Barbudan': 'AG',
    'Argentine': 'AR',
    'Armenian': 'AM',
    'Aruban': 'AW',
    'Australian': 'AU',
    'Austrian': 'AT',
    'Azerbaijani, Azeri': 'AZ',
    'Bahamian': 'BS',
    'Bahraini': 'BH',
    'Bangladeshi': 'BD',
    'Barbadian': 'BB',
    'Belarusian': 'BY',
    'Belgian': 'BE',
    'Belizean': 'BZ',
    'Beninese, Beninois': 'BJ',
    'Bermudian, Bermudan': 'BM',
    'Bhutanese': 'BT',
    'Bolivian': 'BO',
    'Bonaire': 'BQ',
    'Bosnian or Herzegovinian': 'BA',
    'Motswana, Botswanan': 'BW',
    'Bouvet Island': 'BV',
    'Brazilian': 'BR',
    'BIOT': 'IO',
    'Bruneian': 'BN',
    'Bulgarian': 'BG',
    'Burkinabé': 'BF',
    'Burundian': 'BI',
    'Cabo Verdean': 'CV',
    'Cambodian': 'KH',
    'Cameroonian': 'CM',
    'Canadian': 'CA',
    'Caymanian': 'KY',
    'Central African': 'CF',
    'Chadian': 'TD',
    'Chilean': 'CL',
    'Chinese': 'CN',
    'Christmas Island': 'CX',
    'Cocos Island': 'CC',
    'Colombian': 'CO',
    'Comoran, Comorian': 'KM',
    'Congolese': 'CD',
    'Cook Island': 'CK',
    'Costa Rican': 'CR',
    'Ivorian': 'CI',
    'Croatian': 'HR',
    'Cuban': 'CU',
    'Curaçaoan': 'CW',
    'Cypriot': 'CY',
    'Czech': 'CZ',
    'Danish': 'DK',
    'Djiboutian': 'DJ',
    'Dominican': 'DO',
    'Ecuadorian': 'EC',
    'Egyptian': 'EG',
    'Salvadoran': 'SV',
    'Equatorial Guinean, Equatoguinean': 'GQ',
    'Eritrean': 'ER',
    'Estonian': 'EE',
    'Ethiopian': 'ET',
    'Falkland Island': 'FK',
    'Faroese': 'FO',
    'Fijian': 'FJ',
    'Finnish': 'FI',
    'French': 'FR',
    'French Guianese': 'GF',
    'French Polynesian': 'PF',
    'French Southern Territories': 'TF',
    'Gabonese': 'GA',
    'Gambian': 'GM',
    'Georgian': 'GE',
    'German': 'DE',
    'Ghanaian': 'GH',
    'Gibraltar': 'GI',
    'Greek, Hellenic': 'GR',
    'Greenlandic': 'GL',
    'Grenadian': 'GD',
    'Guadeloupe': 'GP',
    'Guamanian, Guambat': 'GU',
    'Guatemalan': 'GT',
    'Channel Island': 'JE',
    'Guinean': 'GN',
    'Bissau-Guinean': 'GW',
    'Guyanese': 'GY',
    'Haitian': 'HT',
    'Heard Island or McDonald Islands': 'HM',
    'Vatican': 'VA',
    'Honduran': 'HN',
    'Hong Kong, Hong Kongese': 'HK',
    'Hungarian, Magyar': 'HU',
    'Icelandic': 'IS',
    'Indian': 'IN',
    'Indonesian': 'ID',
    'Iranian, Persian': 'IR',
    'Iraqi': 'IQ',
    'Irish': 'IE',
    'Manx': 'IM',
    'Israeli': 'IL',
    'Italian': 'IT',
    'Jamaican': 'JM',
    'Japanese': 'JP',
    'Jordanian': 'JO',
    'Kazakhstani, Kazakh': 'KZ',
    'Kenyan': 'KE',
    'I-Kiribati': 'KI',
    'North Korean': 'KP',
    'South Korean': 'KR',
    'Kuwaiti': 'KW',
    'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz': 'KG',
    'Lao, Laotian': 'LA',
    'Latvian': 'LV',
    'Lebanese': 'LB',
    'Basotho': 'LS',
    'Liberian': 'LR',
    'Libyan': 'LY',
    'Liechtenstein': 'LI',
    'Lithuanian': 'LT',
    'Luxembourg, Luxembourgish': 'LU',
    'Macanese, Chinese': 'MO',
    'Macedonian': 'MK',
    'Malagasy': 'MG',
    'Malawian': 'MW',
    'Malaysian': 'MY',
    'Maldivian': 'MV',
    'Malian, Malinese': 'ML',
    'Maltese': 'MT',
    'Marshallese': 'MH',
    'Martiniquais, Martinican': 'MQ',
    'Mauritanian': 'MR',
    'Mauritian': 'MU',
    'Mahoran': 'YT',
    'Mexican': 'MX',
    'Micronesian': 'FM',
    'Moldovan': 'MD',
    'Monégasque, Monacan': 'MC',
    'Mongolian': 'MN',
    'Montenegrin': 'ME',
    'Montserratian': 'MS',
    'Moroccan': 'MA',
    'Mozambican': 'MZ',
    'Burmese': 'MM',
    'Namibian': 'NA',
    'Nauruan': 'NR',
    'Nepali, Nepalese': 'NP',
    'Dutch, Netherlandic': 'NL',
    'New Caledonian': 'NC',
    'New Zealand, NZ': 'NZ',
    'Nicaraguan': 'NI',
    'Nigerien': 'NE',
    'Nigerian': 'NG',
    'Niuean': 'NU',
    'Norfolk Island': 'NF',
    'Northern Marianan': 'MP',
    'Norwegian': 'NO',
    'Omani': 'OM',
    'Pakistani': 'PK',
    'Palauan': 'PW',
    'Palestinian': 'PS',
    'Panamanian': 'PA',
    'Papua New Guinean, Papuan': 'PG',
    'Paraguayan': 'PY',
    'Peruvian': 'PE',
    'Philippine, Filipino': 'PH',
    'Pitcairn Island': 'PN',
    'Polish': 'PL',
    'Portuguese': 'PT',
    'Puerto Rican': 'PR',
    'Qatari': 'QA',
    'Réunionese, Réunionnais': 'RE',
    'Romanian': 'RO',
    'Russian': 'RU',
    'Rwandan': 'RW',
    'Barthélemois': 'BL',
    'Saint Helenian': 'SH',
    'Kittitian or Nevisian': 'KN',
    'Saint Lucian': 'LC',
    'Saint-Martinoise': 'MF',
    'Saint-Pierrais or Miquelonnais': 'PM',
    'Saint Vincentian, Vincentian': 'VC',
    'Samoan': 'WS',
    'Sammarinese': 'SM',
    'Sao Toméan': 'ST',
    'Saudi, Saudi Arabian': 'SA',
    'Senegalese': 'SN',
    'Serbian': 'RS',
    'Seychellois': 'SC',
    'Sierra Leonean': 'SL',
    'Singaporean': 'SG',
    'Sint Maarten': 'SX',
    'Slovak': 'SK',
    'Slovenian, Slovene': 'SI',
    'Solomon Island': 'SB',
    'Somali, Somalian': 'SO',
    'South African': 'ZA',
    'South Georgia or South Sandwich Islands': 'GS',
    'South Sudanese': 'SS',
    'Spanish': 'ES',
    'Sri Lankan': 'LK',
    'Sudanese': 'SD',
    'Surinamese': 'SR',
    'Svalbard': 'SJ',
    'Swazi': 'SZ',
    'Swedish': 'SE',
    'Swiss': 'CH',
    'Syrian': 'SY',
    'Chinese, Taiwanese': 'TW',
    'Tajikistani': 'TJ',
    'Tanzanian': 'TZ',
    'Thai': 'TH',
    'Timorese': 'TL',
    'Togolese': 'TG',
    'Tokelauan': 'TK',
    'Tongan': 'TO',
    'Trinidadian or Tobagonian': 'TT',
    'Tunisian': 'TN',
    'Turkish': 'TR',
    'Turkmen': 'TM',
    'Turks and Caicos Island': 'TC',
    'Tuvaluan': 'TV',
    'Ugandan': 'UG',
    'Ukrainian': 'UA',
    'Emirati, Emirian, Emiri': 'AE',
    'British, UK': 'GB',
    'American': 'US',
    'Uruguayan': 'UY',
    'Uzbekistani, Uzbek': 'UZ',
    'Ni-Vanuatu, Vanuatuan': 'VU',
    'Venezuelan': 'VE',
    'Vietnamese': 'VN',
    'British Virgin Island': 'VG',
    'U.S. Virgin Island': 'VI',
    'Wallis and Futuna, Wallisian or Futunan': 'WF',
    'Sahrawi, Sahrawian, Sahraouian': 'EH',
    'Yemeni': 'YE',
    'Zambian': 'ZM',
    'Zimbabwean': 'ZW'
  };

  
  export default nationalityToAlpha2;